name: Run CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  synthetic_ci:
    runs-on: ubuntu-latest
    name: Run OpenStatus Synthetics CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run OpenStatus Synthetics CI
        uses: openstatushq/openstatus-github-action@953c279982ddf348eb77c54313207655378ac5dc
        with:
          api_key: ${{ secrets.OPENSTATUS_API_KEY }}
